language: java

sudo: false

jdk:
    - oraclejdk8

install: mvn install -DskipTests -Dgpg.skip

script:
    - mvn clean verify -Dgpg.skip

after_success:
    - mvn clean cobertura:cobertura coveralls:report -Dgpg.skip

cache:
  directories:
  - $HOME/.m2
