language: java

sudo: false

jdk:
    - openjdk8

install:
    - export JAVA_TOOL_OPTIONS="-Dfile.encoding=UTF8"
    - mvn install -DskipTests -Dgpg.skip

script:
    - export JAVA_TOOL_OPTIONS="-Dfile.encoding=UTF8"
    - mvn verify -Dgpg.skip

after_success:
    - export JAVA_TOOL_OPTIONS="-Dfile.encoding=UTF8"
    - mvn coveralls:report -Dgpg.skip

cache:
  directories:
  - $HOME/.m2
